platform:ios, '10.0'
target 'iOSDemo' do


pod 'AFNetworking' # (4.0.1)
pod 'SVProgressHUD' # (2.2.5)

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] ='10.0'
    end
  end
end


end
